name: Go Test, Build and Deploy

on:
  push:
    branches:
      - main
 
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.23.4
      
    - name: Test
      run: go test -v ./...
      
    - name: Build
      run: go build -v -o topbot ./cmd/bot

    - uses: actions/upload-artifact@v3
      with:
          name: topbot-artifact
          path: ./topbot

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: topbot-artifact
      - name: Deploy to server
        uses: appleboy/scp-action@master
        with:
           host: ${{ secrets.HOST }}
           username: ${{ secrets.USERNAME }}
           password: ${{ secrets.PASSWORD }}
           port: ${{ secrets.PORT }}
           source: ./topbot
           target: "/home/${{ secrets.USERNAME }}/projects/top-bot"

      - name: Start ChessBot Swahili  service and Reload Nginx
        uses: appleboy/ssh-action@master
        with:
           host: ${{ secrets.HOST }}
           username: ${{ secrets.USERNAME }}
           password: ${{ secrets.PASSWORD }}
           port: ${{ secrets.PORT }}
           script: |
               cd  /home/${{ secrets.USERNAME }}/projects/top-bot
               chmod +x topbot
               echo ${{ secrets.PASSWORD }} | sudo -S systemctl stop topbot.service 
               echo ${{ secrets.PASSWORD }} | sudo -S systemctl start topbot.service 
               echo ${{ secrets.PASSWORD }} | sudo -S systemctl reload nginx

 
